language: python

python: 2.7

envlist =
    py27-django{17,111},
    py35-django{17,_trunk},
    py36-django{17,18,19,110,111,_trunk},

[testenv]
basepython =
    py27: python2.7
    py35: python3.5
    py36: python3.6
env:
  - TOXENV=py27-django17
  - TOXENV=py27-django_111
  - TOXENV=py35-django17
  - TOXENV=py35-django_trunk
  - TOXENV=py36-django18
  - TOXENV=py36-django19
  - TOXENV=py36-django110
  - TOXENV=py36-django111
  - TOXENV=py36-django_trunk

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - python3.6

notifications:
  email: false

install:
  - pip install --upgrade pip setuptools tox virtualenv coveralls

script:
  - tox

matrix:
  allow_failures:
    - env: TOXENV=py35-django_trunk
    - env: TOXENV=py36-django_trunk

after_success: coveralls
